name: Run deploy

on: [workflow_dispatch]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Set up WireGuard
              uses: egor-tensin/setup-wireguard@v1
              with:
                endpoint: ${{ vars.WIREGUARD_HOST }}:${{ vars.WIREGUARD_PORT }}
                endpoint_public_key: ${{ vars.WIREGUARD_PUBLIC_KEY }}
                ips: ${{ vars.WIREGUARD_INTERFACE_IP }}
                allowed_ips: ${{ vars.WIREGUARD_ADDITIONAL_IPS }}, ${{ vars.WIREGUARD_INTERFACE_IP }}, ${{ secrets.SSH_HOST }}
                private_key: '${{ secrets.WIREGUARD_PRIVATE_KEY }}'

            - name: SSH proxy command
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: "${{ vars.DEPLOY_SCRIPT }}"
